# Generated by Django 5.0.6 on 2024-08-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='adress',
            field=models.TextField(max_length=500, verbose_name='Address'),
        ),
    ]
