# Generated by Django 5.0.6 on 2024-07-31 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Vaccine Name')),
                ('description', models.TextField(max_length=1024)),
                ('numbre_of_doses', models.IntegerField(default=1)),
                ('interval', models.IntegerField(default=0, help_text='please provide interval in days')),
                ('storage_temprature', models.IntegerField(blank=True, help_text='provide temprature in celcius', null=True)),
                ('minimum_age', models.IntegerField(default=0)),
            ],
        ),
    ]
