# Generated by Django 5.0.6 on 2024-07-31 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vacine',
            new_name='Vaccine',
        ),
    ]
